# Generated by fluxon_cxx/build.rs
add_library(FluxonNative::runtime INTERFACE IMPORTED)

set_target_properties(FluxonNative::runtime PROPERTIES
  INTERFACE_LINK_LIBRARIES "$ORIGIN/../../libfluxon_rdma_probe.so;-lz;-lnuma;$ORIGIN/../../../vendor_runtime/lib/libibverbs.so;$ORIGIN/../../../vendor_runtime/lib/libnl-3.so;$ORIGIN/../../../vendor_runtime/lib/libnl-route-3.so"
)
