use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const ENV_GIT_COMMIT_HASH: &str = "GIT_COMMIT_HASH";
const ENV_SOURCE_SHA256: &str = "FLUXON_RS_SOURCE_SHA256";

struct CargoWorkspace {
    workspace_root: PathBuf,
    member_packages: Vec<CargoPackage>,
}

struct CargoPackage {
    name: String,
    manifest_path: PathBuf,
}

fn load_cargo_workspace(manifest_dir: &Path) -> CargoWorkspace {
    let cargo = env::var("CARGO").unwrap();
    let output = Command::new(cargo)
        .current_dir(manifest_dir)
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .output()
        .expect("failed to run `cargo metadata`");
    if !output.status.success() {
        panic!("cargo metadata failed: status={:?}", output.status);
    }

    let meta: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("parse cargo metadata json");
    let ws_root = meta["workspace_root"]
        .as_str()
        .expect("workspace_root string");
    let ws_members = meta["workspace_members"]
        .as_array()
        .expect("workspace_members array");
    let packages = meta["packages"].as_array().expect("packages array");

    let mut id_to_pkg: std::collections::HashMap<String, CargoPackage> =
        std::collections::HashMap::new();
    for p in packages {
        let id = p["id"].as_str().unwrap();
        let name = p["name"].as_str().unwrap();
        let manifest_path = p["manifest_path"].as_str().expect("manifest_path string");
        id_to_pkg.insert(
            id.to_string(),
            CargoPackage {
                name: name.to_string(),
                manifest_path: PathBuf::from(manifest_path),
            },
        );
    }

    let mut member_packages: Vec<CargoPackage> = ws_members
        .iter()
        .map(|id| id.as_str().unwrap())
        .map(|id| {
            id_to_pkg
                .remove(id)
                .unwrap_or_else(|| panic!("missing workspace member package: {}", id))
        })
        .collect();
    member_packages.sort_by(|a, b| a.name.cmp(&b.name));

    CargoWorkspace {
        workspace_root: PathBuf::from(ws_root),
        member_packages,
    }
}

fn collect_crates_for_runtime(ws: &CargoWorkspace) {
    // Generate Rust source with a public const slice
    let mut out = String::new();
    out.push_str("// @generated by build.rs; DO NOT EDIT\n");
    out.push_str("pub const OUR_CRATES: &[&str] = &[\n");
    for p in &ws.member_packages {
        out.push_str(&format!("    \"{}\",\n", p.name));
    }
    out.push_str("];");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("our_crates.rs");
    fs::write(&dest, out).expect("write our_crates.rs");
    // Re-run build script when workspace membership may change.
    println!("cargo:rerun-if-changed=../Cargo.toml");
    println!("cargo:rerun-if-changed=Cargo.toml");
}

fn try_discover_git_dir(manifest_dir: &Path, workspace_root: &Path) -> Option<PathBuf> {
    let workspace_search_ceiling = workspace_root.parent().unwrap_or(workspace_root);
    let mut cur = Some(manifest_dir);
    while let Some(dir) = cur {
        let candidate = dir.join(".git");
        if candidate.is_dir() {
            if candidate.join("HEAD").is_file() {
                return Some(candidate);
            }
        }
        if candidate.is_file() {
            // Worktree/submodule style: .git is a file containing `gitdir: <path>`
            let content = fs::read_to_string(&candidate).unwrap_or_else(|e| {
                panic!("read .git file failed: {} (err={})", candidate.display(), e)
            });
            let content = content.trim();
            let gitdir = content
                .strip_prefix("gitdir:")
                .unwrap_or_else(|| panic!("invalid .git file format: {}", candidate.display()))
                .trim();
            let gitdir_path = Path::new(gitdir);
            let resolved = if gitdir_path.is_absolute() {
                gitdir_path.to_path_buf()
            } else {
                dir.join(gitdir_path)
            };
            if resolved.join("HEAD").is_file() {
                return Some(resolved);
            }
        }
        if dir == workspace_search_ceiling {
            break;
        }
        cur = dir.parent();
    }
    None
}

fn parse_packed_refs(git_dir: &Path, want_ref: &str) -> Option<String> {
    let packed_refs = git_dir.join("packed-refs");
    let content = fs::read_to_string(packed_refs).ok()?;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('^') {
            continue;
        }
        let (hash, rf) = line.split_once(' ')?;
        if rf == want_ref {
            return Some(hash.to_string());
        }
    }
    None
}

fn resolve_head_commit_id(git_dir: &Path) -> String {
    let head_path = git_dir.join("HEAD");
    let head = fs::read_to_string(&head_path)
        .unwrap_or_else(|e| panic!("read HEAD failed: {} (err={})", head_path.display(), e));
    let head = head.trim();

    let hash = if let Some(rest) = head.strip_prefix("ref:") {
        let rf = rest.trim();
        let ref_path = git_dir.join(rf);
        match fs::read_to_string(&ref_path) {
            Ok(s) => s.trim().to_string(),
            Err(_) => parse_packed_refs(git_dir, rf).unwrap_or_else(|| {
                panic!(
                    "cannot resolve git HEAD ref (missing ref file and packed-refs entry): {} (ref={})",
                    ref_path.display(),
                    rf
                )
            }),
        }
    } else {
        head.to_string()
    };

    if hash.len() != 40 || !hash.chars().all(|c| c.is_ascii_hexdigit()) {
        panic!("invalid git commit hash resolved from HEAD: {}", hash);
    }
    hash
}

fn list_rs_files_recursively(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir failed: {} (err={})", dir.display(), e));
    for entry in entries {
        let entry = entry
            .unwrap_or_else(|e| panic!("read_dir entry failed: {} (err={})", dir.display(), e));
        let path = entry.path();
        let ty = entry
            .file_type()
            .unwrap_or_else(|e| panic!("file_type failed: {} (err={})", path.display(), e));
        if ty.is_dir() {
            list_rs_files_recursively(&path, out);
            continue;
        }
        if ty.is_file()
            && path
                .extension()
                .is_some_and(|ext| ext == std::ffi::OsStr::new("rs"))
        {
            out.push(path);
        }
    }
}

fn compute_workspace_source_sha256(ws: &CargoWorkspace) -> String {
    let mut files: Vec<PathBuf> = vec![
        ws.workspace_root.join("Cargo.toml"),
        ws.workspace_root.join("Cargo.lock"),
    ];

    for pkg in &ws.member_packages {
        files.push(pkg.manifest_path.clone());
        let crate_dir = pkg
            .manifest_path
            .parent()
            .unwrap_or_else(|| panic!("invalid manifest_path: {}", pkg.manifest_path.display()));

        let build_rs = crate_dir.join("build.rs");
        if build_rs.exists() {
            files.push(build_rs);
        }

        let src_dir = crate_dir.join("src");
        if src_dir.exists() {
            list_rs_files_recursively(&src_dir, &mut files);
        }
    }

    let mut items: Vec<(String, PathBuf)> = files
        .into_iter()
        .map(|abs| {
            let rel = abs
                .strip_prefix(&ws.workspace_root)
                .unwrap_or(&abs)
                .to_string_lossy()
                .to_string();
            (rel, abs)
        })
        .collect();
    items.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = Sha256::new();
    for (rel, abs) in items {
        let data = fs::read(&abs).unwrap_or_else(|e| {
            panic!(
                "read source file for checksum failed: {} (err={})",
                abs.display(),
                e
            )
        });
        hasher.update(rel.as_bytes());
        hasher.update([0]);
        hasher.update((data.len() as u64).to_le_bytes());
        hasher.update(data);
    }

    hex::encode(hasher.finalize())
}

fn emit_rerun_hints(git_dir: &Path) {
    // Always watch HEAD.
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());

    // For normal branch commits, HEAD usually points to a ref file; that ref file changes.
    if let Ok(head) = fs::read_to_string(git_dir.join("HEAD")) {
        let head = head.trim();
        if let Some(rest) = head.strip_prefix("ref:") {
            let ref_path = git_dir.join(rest.trim());
            println!("cargo:rerun-if-changed={}", ref_path.display());
        }
    }

    // Extra safety: packed refs can affect resolution.
    let packed_refs = git_dir.join("packed-refs");
    if packed_refs.exists() {
        println!("cargo:rerun-if-changed={}", packed_refs.display());
    }
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));

    // Always re-run if this build script changes, even when the build comes from a source snapshot
    // without any .git metadata (e.g. CI unpacking src_ci.tar.gz).
    println!("cargo:rerun-if-changed=build.rs");

    let ws = load_cargo_workspace(&manifest_dir);
    println!(
        "cargo:rerun-if-changed={}",
        ws.workspace_root.join("Cargo.toml").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        ws.workspace_root.join("Cargo.lock").display()
    );
    for pkg in &ws.member_packages {
        println!("cargo:rerun-if-changed={}", pkg.manifest_path.display());
        let crate_dir = pkg
            .manifest_path
            .parent()
            .unwrap_or_else(|| panic!("invalid manifest_path: {}", pkg.manifest_path.display()));
        let src_dir = crate_dir.join("src");
        if src_dir.exists() {
            println!("cargo:rerun-if-changed={}", src_dir.display());
        }
        let build_rs = crate_dir.join("build.rs");
        if build_rs.exists() {
            println!("cargo:rerun-if-changed={}", build_rs.display());
        }
    }

    let source_sha256 = compute_workspace_source_sha256(&ws);
    println!("cargo:rustc-env={}={}", ENV_SOURCE_SHA256, source_sha256);

    let git_hash = match env::var(ENV_GIT_COMMIT_HASH) {
        Ok(v) => {
            if v.len() != 40 || !v.chars().all(|c| c.is_ascii_hexdigit()) {
                panic!(
                    "invalid {} provided via environment: {}",
                    ENV_GIT_COMMIT_HASH, v
                );
            }
            println!("cargo:rerun-if-env-changed={}", ENV_GIT_COMMIT_HASH);
            v
        }
        Err(_) => {
            match try_discover_git_dir(&manifest_dir, &ws.workspace_root) {
                Some(git_dir) => {
                    emit_rerun_hints(&git_dir);
                    resolve_head_commit_id(&git_dir)
                }
                None => {
                    // Causal chain:
                    // - CI runs from src_ci.tar.gz extracted into a run-scoped workdir.
                    // - The CI source tarball intentionally excludes .git to keep the artifact small and portable.
                    // - Therefore build.rs must not panic when .git is missing, otherwise `cargo test --no-run`
                    //   fails even though the source snapshot is valid.
                    //
                    // Use a deterministic build identifier derived from the exact source snapshot.
                    let pseudo = source_sha256
                        .get(0..40)
                        .expect("source sha256 must be 64 hex chars");
                    println!(
                        "cargo:warning=GIT_COMMIT_HASH not provided and .git not found; using FLUXON_RS_SOURCE_SHA256 prefix: {}",
                        pseudo
                    );
                    pseudo.to_string()
                }
            }
        }
    };
    println!("cargo:rustc-env={}={}", ENV_GIT_COMMIT_HASH, git_hash);
    println!("{}={}", ENV_GIT_COMMIT_HASH, git_hash); // For visibility in build logs

    collect_crates_for_runtime(&ws);
}
